{% set name = "freecad" %}
{% set version = "0.18b0" %}


package:
    name: {{ name }}
    version: {{ version }}

source:
    git_url: https://github.com/FreeCAD/FreeCAD
    git_tag: master
    patches:
        - osx.patch  # [osx]

build:
    number: 38

requirements:
    build:
        - {{ compiler("cxx") }}
        - cmake
        - ninja
        - git
    host:
        - tbb-devel
        - boost-cpp
        - python
        - qt
        - qtwebkit  # [osx]
        - occt
        - xerces-c
        - zlib
        - vtk 8.1.1
        - swig
        - eigen
        - pybind11
        - matplotlib
        - coin3d
        - pivy
        - pyside2
        - smesh
        - netgen 6.2.1808
        - doxygen
        - hdf5 1.10.1
        - libglu  # [linux]
        - mesalib  # [linux]
        - xorg-libxi  # [linux]
        - xorg-libxmu  # [linux]
        - xorg-libxt  # [linux]
        - blas * openblas
    run:
        - {{ pin_compatible("pyside2") }}
        - occt
        - vtk
        - qt
        - qtwebkit  # [osx]
        - xerces-c
        - zlib
        - boost-cpp
        - hdf5
        - python
        - numpy
        - matplotlib
        - coin3d
        - pivy
        - smesh
        - netgen 6.2.1808
        - libglu  # [linux]
        - mesalib  # [linux]
        - xorg-libxi  # [linux]
        - xorg-libxmu  # [linux]
        - xorg-libxt  # [linux]

test:
    commands:
        - FreeCADCmd -t 0

about:
    home: https://www.freecadweb.org/
    license: LGPL2
    license_family: LGPL
    license_file: LICENSE
    summary: 'FreeCAD is a parametric 3D modeler made primarily to design real-life objects of any size. '
    description: |
        FreeCAD is a general purpose feature-based, parametric 3D modeler for
        CAD, MCAD, CAx, CAE and PLM, aimed directly at mechanical engineering
        and product design but also fits a wider range of uses in engineering,
        such as architecture or other engineering specialties. It is 100% Open
        Source (LGPL2+ license) and extremely modular, allowing for very
        advanced extension and customization.
        FreeCAD is based on OpenCASCADE, a powerful geometry kernel, features an
        Open Inventor-compliant 3D scene representation model provided by the
        Coin 3D library, and a broad Python API. The interface is built with Qt.
        FreeCAD runs exactly the same way on Windows, Mac OSX, BSD and Linux
        platforms.
    doc_url: https://www.freecadweb.org/wiki/Main_Page
    dev_url: https://github.com/FreeCAD/FreeCAD

extra:
    recipe-maintainers:
        - looooo
