travis:
  secure:
    BINSTAR_TOKEN: uQjFH3O3gBSTkFCrVSr2Vlt2dxi+Qx3Q98TLNMK6gTEyNz9RbCiGge1Y6hAsm65cCtKjU0u4xUceZw5MVaW/kNGEqtgiJI93VxLIet/fA3SgLx41zx7t4CG++P0qiVo9US2HoX2I70GtJ1kA3LM4K82lLjmC2EqV5a8YNTKK9FcN4gAR1zsF5y1vdgdNQAZU09pjXSn1cs/bhkxE6TVKXacccJi4ACTNgLRdhhHqxmvOJPMs3bvQgANNEMiOjro6D98d8XyxKCnku1xFpFG8xmiFXYog09dIcBdUSENkXuMTD7cBofjQ/XA4lKZnAyrr/lY3YwDqvhsuKoEp7H0Q10DNcFVTi7LVBKc83sv1oJzBPB3XkHtFLUsC1joZl+8XW/ALILL/itf5u/jHMxJ41yubW11z3LJn9+nzkUx7uDbZEbVNa//yNFdtzgJRWnpHb83oFKcdx0dIqFNKLOpHQSSEg5GEiOkeeJh5Y2Lenj36QT0ll6cmAs5w84SwV9z4isgTJ0cG3IGWY0TpP6rMqBhBbX1MtktT7+z2j+ZU8EmM4RNv97SGacm/0bALNfL1PzLqnfw26ml9tqfQaAE2IPViSoaedDmTdJYub445Kj4YIPDQxbRInQpYkOixE4gbxZUkxAblKZuBGpOSWS46R057oglp4H9dhB/qfMVRD48=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1

provider:
  osx: circle
